format_version: v1.0
type: GroupComponent
attributes: {displayName: BASIC CONFIGURATION, id: BASIC CONFIGURATION}
children:
- type: ElementPosition
  attributes: {x: '252', y: '83', id: BASIC CONFIGURATION}
- type: Attachments
  children:
  - type: Attachment
    attributes: {namespace: tcpipNetConfig_0, id: NETCONFIG_MAC_Dependency}
