format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiPic32mzw1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_WIFI_PIC32MZW1_ALARM_PERIOD_1MS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: '195'}
  - type: Integer
    attributes: {id: DRV_WIFI_PIC32MZW1_ALARM_PERIOD_MAX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: '336'}
  - type: Combo
    attributes: {id: DRV_WIFI_PIC32MZW1_LOG_LEVEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: Verbose}
  - type: Boolean
    attributes: {id: DRV_WIFI_PIC32MZW1_REQUIRE_BA414E}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_PIC32MZW1_SUPPORT_WPA3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: 'false'}
  - type: File
    attributes: {id: DRV_WIFI_PIC32MZW1_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_PIC32MZW1_USE_SYS_DEBUG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiPic32mzw1, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: BA414E_Dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: libdrvPic32mzw1Mac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tcpipNetConfig_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NETCONFIG_MAC_Dependency}
- type: ElementPosition
  attributes: {x: '30', y: '160', id: drvWifiPic32mzw1}
