format_version: v1.0
type: UniqueComponent
attributes: {id: net_Pres}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_CERT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '0'}
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_CERT_REPO}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_CERT_FILENAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: wolfssl/certs_test.h}
      - type: User
        attributes: {value: app.h}
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_CLIENT_CERT_FORMAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '1'}
      - type: User
        attributes: {value: '1'}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_CERT_LEN_VARIABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: sizeof_client_cert_der_2048}
      - type: User
        attributes: {value: appData.caCert_len}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_CERT_VARIABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: client_cert_der_2048}
      - type: User
        attributes: {value: appData.caCert}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_DEVICE_CERT_LEN_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: appData.deviceCert_len}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_DEVICE_CERT_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: appData.deviceCert}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_DEVICE_PVT_KEY_LEN_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: appData.devicePvtKey_len}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_DEVICE_PVT_KEY_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: appData.devicePvtKey}
  - type: String
    attributes: {id: NET_PRES_BLOB_CLIENT_MUTUAL_AUTH_FILENAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: app.h}
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_CLIENT_MUTUAL_AUTH_FORMAT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_CLIENT_MUTUAL_AUTH_SUPPORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_CLIENT_SUPPORT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_ENABLE_PEER_CERT_VERIFICATION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_CERT_FILENAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: wolfssl/certs_test.h}
  - type: KeyValueSet
    attributes: {id: NET_PRES_BLOB_SERVER_CERT_FORMAT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '1'}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_CERT_LEN_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: sizeof_server_cert_der_2048}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_CERT_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: server_cert_der_2048}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_KEY_FILENAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: wolfssl/certs_test.h}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_KEY_LEN_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: sizeof_server_key_der_2048}
  - type: String
    attributes: {id: NET_PRES_BLOB_SERVER_KEY_VARIABLE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: server_key_der_2048}
  - type: Boolean
    attributes: {id: NET_PRES_BLOB_SERVER_SUPPORT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_CERT_STORE_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_CERT_STORE_STUBS_CLIENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: NET_PRES_CERT_STORE_STUBS_SERVER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: NET_PRES_ENC_PROVIDE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '0'}
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: NET_PRES_GENERATE_ENC_STUBS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'false'}
  - type: Integer
    attributes: {id: NET_PRES_RTOS_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: '20480'}
  - type: Integer
    attributes: {id: NET_PRES_SOCKETS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_CLIENT_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_DATAGRAM_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_ENCRYPTION}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_SERVER_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_SUPPORT_STREAM_ENC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: NET_PRES_USE_WOLF_SSL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: net_Pres, value: 'true'}
- type: ElementPosition
  attributes: {x: '296', y: '259', id: net_Pres}
