format_version: v1.0
type: GroupComponent
attributes: {displayName: System Configuration, id: System Configuration}
children:
- type: ElementPosition
  attributes: {x: '264', y: '142', id: System Configuration}
