format_version: v1.0
type: UniqueComponent
attributes: {id: sysNetPic32mzw1}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SYS_NET_ENABLE_TLS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: SYS_NET_HOST_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: dp-sps-na.amazon.com}
- type: ElementPosition
  attributes: {x: '110', y: '392', id: sysNetPic32mzw1}
