configName: pic32mz_w1_curiosity_freertos
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: crypto;dev_packs;net;core;bsp;csp_apps_pic32mz_w1;quick_docs;usb;cryptoauthlib;wireless_wifi;csp;harmony-services;wireless_system_pic32mzw1_wfi32e01;wireless_apps_pic32mzw1_wfi32e01;aws_cloud
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: ./dev_packs/arm/CMSIS/5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: ./dev_packs/Microchip/PIC32MZ-W_DFP/1.5.203/atdf/PIC32MZ1025W104132.atdf
